POST http://localhost:8000/v1/delivery
Content-Type: application/json

[{
  "shipmentLocationId": 1,
  "receiptLocationId": 2,
  "waybillNo": "100",
  "boxNo": "100",
  "type": "HubLabs",
  "items": [
    {
      "skuId": 1,
      "qty": 10
    },
    {
      "skuId": 2,
      "qty": 2
    }
  ],
  "createdBy": "li.dongxun"
}, {
  "shipmentLocationId": 1,
  "receiptLocationId": 2,
  "waybillNo": "210",
  "boxNo": "210",
  "type": "HubLabs",
  "items": [
    {
      "skuId": 66,
      "qty": 10
    },
    {
      "skuId": 55,
      "qty": 2
    }
  ],
  "createdBy": "li.dongxun"
}]

###