// ref：https://sundo.kim/1032
POST {{delivery-api}}/v1/stock
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="locationId";

1

--WebAppBoundary
Content-Disposition: form-data; name="createdBy";

li.dongxun

--WebAppBoundary
Content-Disposition: form-data; name="type";

store

--WebAppBoundary
Content-Disposition: form-data; name="stockFile"; filename="init_stock.xlsx"

< ../init_stock.xlsx
--WebAppBoundary--

###

POST {{delivery-api}}/v1/stock
Content-Type: application/json
Authorization: {{token}}

{
  "locationId": 1,
  "createdBy": "li.dongxun",
  "type": "store",
  "items": [
    {
      "skuId": 100,
      "qty": 10
    },
    {
      "skuId": 200,
      "qty": 20
    },
    {
      "skuId": 300,
      "qty": 22
    }
  ]
}

###
POST {{delivery-api}}/v1/stock
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="locationId";

1

--WebAppBoundary
Content-Disposition: form-data; name="createdBy";

li.dongxun

--WebAppBoundary
Content-Disposition: form-data; name="type";

plant

--WebAppBoundary
Content-Disposition: form-data; name="stockFile"; filename="init_stock.xlsx"

< ../init_stock.xlsx
--WebAppBoundary--

###

POST {{delivery-api}}/v1/stock
Content-Type: application/json
Authorization: {{token}}

{
  "locationId": 1,
  "createdBy": "li.dongxun",
  "type": "plant",
  "items": [
    {
      "skuId": 100,
      "qty": 10
    },
    {
      "skuId": 200,
      "qty": 20
    },
    {
      "skuId": 300,
      "qty": 22
    }
  ]
}

###
